### ISSUE TITLE
plugins folder vs. single js file

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/IPS-EMUprot-nodeWSserver#4]
@MJochim currently every plugin has to be contained in a single JavaScript file. Just in case we write more involved plugins in the future, do you it might be a better idea to use a subfolder per plugin ala:
```
plugins/bas-guest-access/main.js
plugins/bas-guest-access/externalFile.jso
...
```
Where the `main.js` file is obligatory (or maybe there is a node.js convention that I am not aware of that we could use?). 

?

**Comment by MJochim** [comment]
I'd stick with the current way. If the need arises, there is still this possibility:

```
plugins/my-cool-plugin.js
plugins/my-cool-plugin/wow-what-a-module.js
plugins/my-cool-plugin/helper-functions.js
```

Anyway, I do not expect any plugins that complicated any time soon.

**Comment by raphywink** [comment]
Oki doki! Then we leave it the way it is for now...
